In [3]:
pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   -------------------------------- ------- 10.5/12.8 MB 56.0 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 52.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 11.0/11.0 MB 69.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [90]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
rd = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

In [6]:
rd
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [ ]:
# ## Basic Performance Analysis
# 1. What is the **total revenue** generated across all stores?
# 2. Which store recorded the **highest sales**?
# 3. Which store recorded the **lowest sales**?
# 4. What is the **average daily sales** per store?
# 5. How many stores achieved sales **above ₹35,000**?

# ## Customer Insights
# 6. Which store had the **highest customer footfall**?
# 7. What is the **average number of customers** per store?
# 8. How many stores have **more than 450 customers**?
# 9. Which store has the **lowest customer count**?
# 10. Is there any store where **high sales do not correspond to high customers**?

# ## Inventory & Returns Analysis
# 11. What is the **total inventory** across all stores?
# 12. Which store has the **highest inventory stock**?
# 13. How many stores have **inventory less than 1300 units**?
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
# 15. Which stores have **returns greater than 15 units**?

# ## Sales & Customer Correlation
# 16. Is there a **positive correlation** between sales and customers?
# 17. Which store has **high customer visits but low sales**?
# 18. Which store has **low customers but high sales**?
# 19. How many stores have **sales per customer above ₹90**?
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

# ## Profitability & Growth
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
# 22. Which store has the **highest profit**?
# 23. Which store has the **lowest profit**?
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
# 25. How will **total profit** change with the 10% sales increase?

# ## Operational Strategy
# 26. Which stores need **inventory restocking** based on sales and current stock?
# 27. Which stores show **high returns percentage** and might require **quality checks**?
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
# 29. Which store is the **worst performer overall**?
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

In [83]:
# 1. What is the **total revenue** generated across all stores?
revenue=rd[:,1].sum()
revenue


np.int64(335000)

In [28]:
# 2. Which store recorded the **highest sales**?
highest_sales=rd[:,1].argmax()+1
highest_sales

np.int64(9)

In [29]:
# 3. Which store recorded the **lowest sales**?
lowest_sales=rd[:,1].argmin()+1
lowest_sales

np.int64(1)

In [13]:
# 4. What is the **average daily sales** per store?
avg_sales=rd[:,1].mean()/10
avg_sales

np.float64(3350.0)

In [46]:
# 5. How many stores achieved sales **above ₹35,000**?
above=rd[rd[:,1]>35000]
above[:,0]


array([4, 7, 9])

In [35]:
#  6. Which store had the **highest customer footfall**?
C=rd[:,2].argmax()+1
C


np.int64(9)

In [76]:
# 7. What is the **average number of customers** per store?
avgper_cust=rd[:,2].mean()/10
avgper_cust

np.float64(42.5)

In [39]:
# 8. How many stores have **more than 450 customers**?
more=rd[rd[:,2]>450].shape
more


(3, 5)

In [40]:
# 9. Which store has the **lowest customer count**?
lowest=rd[:,2].argmin()+1
lowest

np.int64(1)

In [ ]:
# 10. Is there any store where **high sales do not correspond to high customers**?


In [41]:
# 11. What is the **total inventory** across all stores?
total_inventry=rd[:,3].sum()
total_inventry

np.int64(14300)

In [43]:
# 12. Which store has the **highest inventory stock**?
higgest_inventry=rd[:,3].argmax()+1
higgest_inventry

np.int64(9)

In [45]:
# 13. How many stores have **inventory less than 1300 units**?
lowest_in=rd[rd[:,3]<1300]
lowest_in[:,0]

array([1, 3, 8])

In [47]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
higgest_return=(rd[:,4]/rd[:,3]).argmax()+1
higgest_inventry


np.int64(9)

In [92]:
# 15. Which stores have **returns greater than 15 units**?
return_greater=rd[rd[:,4]>15]
return_greater[:,0]

array([4, 7, 9])

In [51]:
# 16. Is there a **positive correlation** between sales and customers?
corr=np.corrcoef(rd[:,1]/rd[:,2])
corr

np.float64(1.0)

In [ ]:
# 17. Which store has **high customer visits but low sales**?


In [ ]:
# 18. Which store has **low customers but high sales**?

In [103]:
# 19. How many stores have **sales per customer above ₹90**?
H=rd[:,1]/rd[:,2]
H[H>90]


array([], dtype=float64)